Broaden importlib version
Saw something like:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.5 requires importlib-metadata<2.0.0,>=1.6.0; python_version < "3.8", but you have importlib-metadata 3.10.0 which is incompatible.
poetry-core 1.0.3 requires importlib-metadata<2.0.0,>=1.7.0; python_version >= "2.7" and python_version < "2.8" or python_version >= "3.5" and python_version < "3.8", but you have importlib-metadata 3.10.0 which is incompatible.
Successfully installed importlib-metadata-3.10.0 loguru-0.5.3 poetry-lock-package-0.1.1 typing-extensions-3.7.4.3